
name: Python package

on:
  push:
    branches: [waylay_main]
  pull_request:
    branches: [waylay_main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dev dependencies
        run: make ci-install
      - name: Lint and test
        run: make test
